import { NextRequest, NextResponse } from "next/server";
import { Paddle, Environment } from "@paddle/paddle-node-sdk";

// Initialize Paddle client
const paddle = new Paddle(process.env.PADDLE_API_KEY || "", {
  environment:
    process.env.PADDLE_ENVIRONMENT === "production"
      ? Environment.production
      : Environment.sandbox,
});

export async function POST(req: NextRequest) {
  try {
    const { userEmail, userId, customPriceId } = await req.json();

    const priceId = customPriceId || process.env.PADDLE_PRICE_ID;

    if (!priceId) {
      return NextResponse.json(
        { error: "Price ID is missing." },
        { status: 400 }
      );
    }

    // Create a checkout transaction via Paddle Billing API
    const transaction = await paddle.transactions.create({
      items: [
        {
          priceId: priceId,
          quantity: 1,
        },
      ],
      customData: {
        userId: userId || "anonymous",
        userEmail: userEmail || "",
      },
    });

    // Extract checkout URL generated by Paddle
    const checkoutUrl = transaction.checkout?.url;

    if (!checkoutUrl) {
      return NextResponse.json(
        { error: "Failed to generate checkout URL." },
        { status: 500 }
      );
    }

    return NextResponse.json({ url: checkoutUrl, transactionId: transaction.id });
  } catch (error: any) {
    console.error("Paddle Checkout Error:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}


